// <auto-generated />
namespace MVCTuts.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mymig2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mymig2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103141622595_mymig2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
