// <auto-generated />
namespace MVCTuts.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mymig3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mymig3));
        
        string IMigrationMetadata.Id
        {
            get { return "202103211630075_mymig3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
